# fly.toml app configuration file generated for discord-spidey-bot on 2025-10-10T21:06:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-spidey-bot'
primary_region = 'fra'

[build]

[[vm]]
  size = 'shared-cpu-1x'
